// <auto-generated />
using System;
using CocktailMagician.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CocktailMagician.Data.Migrations
{
    [DbContext(typeof(CocktailMagicianDb))]
    [Migration("20191126184126_spellFix")]
    partial class spellFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CocktailMagician.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<bool>("IsDeleted");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            IsDeleted = false,
                            Latitude = 42.693880999999998,
                            Longitude = 23.330114999999999,
                            Name = "18 str. Aksakov"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            IsDeleted = false,
                            Latitude = 42.701141,
                            Longitude = 23.324477000000002,
                            Name = "28 str. Serdika"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            IsDeleted = false,
                            Latitude = 42.692791,
                            Longitude = 23.330869,
                            Name = "12 str. Tsar Shishman"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            IsDeleted = false,
                            Latitude = 42.698543999999998,
                            Longitude = 23.341951000000002,
                            Name = "17 blvd. Yanko Sakazov"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            IsDeleted = false,
                            Latitude = 43.226818000000002,
                            Longitude = 27.886537000000001,
                            Name = "201 blvd. Slivnitsa"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            IsDeleted = false,
                            Latitude = 43.203812999999997,
                            Longitude = 27.908376000000001,
                            Name = "1 str. Batcho Kiro"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            IsDeleted = false,
                            Latitude = 42.144928999999998,
                            Longitude = 24.755649999999999,
                            Name = "12 str. Knyaginya Maria Luiza"
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Bann", b =>
                {
                    b.Property<string>("Id");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Reason");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Banns");
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Bar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId");

                    b.Property<string>("ImagePath")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Bars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            ImagePath = "/barImages/Motto.jpg",
                            IsDeleted = false,
                            Name = "Motto",
                            PhoneNumber = "+35929872723"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            ImagePath = "/barImages/French75.jpg",
                            IsDeleted = false,
                            Name = "French 75",
                            PhoneNumber = "+359887044557"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            ImagePath = "/barImages/OneMoreBar.jpg",
                            IsDeleted = false,
                            Name = "One More Bar",
                            PhoneNumber = "+359877693735"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            ImagePath = "/barImages/Raketa.jpg",
                            IsDeleted = false,
                            Name = "Rakia Raketa Bar",
                            PhoneNumber = "+35924446111"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 5,
                            ImagePath = "/barImages/ModaBarMyPlace.jpeg",
                            IsDeleted = false,
                            Name = "Moda Bar My Place",
                            PhoneNumber = "+359876000056"
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 6,
                            ImagePath = "/barImages/MartiniBar.jpg",
                            IsDeleted = false,
                            Name = "The Martini Bar",
                            PhoneNumber = "+359893374437"
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 7,
                            ImagePath = "/barImages/Kriloto.jpg",
                            IsDeleted = false,
                            Name = "Kriloto",
                            PhoneNumber = "+359879924799"
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.BarCocktail", b =>
                {
                    b.Property<int>("BarId");

                    b.Property<int>("CocktailId");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("BarId", "CocktailId");

                    b.HasIndex("CocktailId");

                    b.ToTable("BarCocktails");

                    b.HasData(
                        new
                        {
                            BarId = 1,
                            CocktailId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 1,
                            CocktailId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 1,
                            CocktailId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 1,
                            CocktailId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 2,
                            CocktailId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 2,
                            CocktailId = 10,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 2,
                            CocktailId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 2,
                            CocktailId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 3,
                            CocktailId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 3,
                            CocktailId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 3,
                            CocktailId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 3,
                            CocktailId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 3,
                            CocktailId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 4,
                            CocktailId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 4,
                            CocktailId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 4,
                            CocktailId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 4,
                            CocktailId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 4,
                            CocktailId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 5,
                            CocktailId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 5,
                            CocktailId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 5,
                            CocktailId = 10,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 5,
                            CocktailId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 6,
                            CocktailId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 6,
                            CocktailId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 6,
                            CocktailId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 6,
                            CocktailId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 7,
                            CocktailId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 7,
                            CocktailId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 7,
                            CocktailId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 7,
                            CocktailId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 7,
                            CocktailId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            BarId = 7,
                            CocktailId = 10,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.BarReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BarId");

                    b.Property<string>("Comment")
                        .HasMaxLength(500);

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("Rating");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BarId");

                    b.HasIndex("UserId");

                    b.ToTable("BarReviews");
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Plovdiv"
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Cocktails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/cocktailImages/OldFashioned.jpg",
                            IsDeleted = false,
                            Name = "Old Fashioned"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/cocktailImages/Margarita.jpg",
                            IsDeleted = false,
                            Name = "Margarita"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "/cocktailImages/Cosmopolitan.jpg",
                            IsDeleted = false,
                            Name = "Cosmopolitan"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "/cocktailImages/Negroni.jpg",
                            IsDeleted = false,
                            Name = "Negroni"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "/cocktiailImages/MoscowMule.jpg",
                            IsDeleted = false,
                            Name = "Moscow Mule"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "/cocktailImages/Mojito.jpg",
                            IsDeleted = false,
                            Name = "Mojito"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "/cocktailImages/WhiskeySour.jpg",
                            IsDeleted = false,
                            Name = "Whiskey Sour"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "/cocktailImages/Manhattan.jpg",
                            IsDeleted = false,
                            Name = "Manhattan"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "/cocktailImages/Mimosa.jpg",
                            IsDeleted = false,
                            Name = "Mimosa"
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "/cocktailImages/Gimlet.jpg",
                            IsDeleted = false,
                            Name = "Gimlet"
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.CocktailIngredient", b =>
                {
                    b.Property<int>("IngredientId");

                    b.Property<int>("CocktailId");

                    b.Property<bool>("IsDeleted");

                    b.Property<double>("Quatity");

                    b.HasKey("IngredientId", "CocktailId");

                    b.HasIndex("CocktailId");

                    b.ToTable("CocktailIngredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            CocktailId = 1,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 2,
                            CocktailId = 1,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 3,
                            CocktailId = 1,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 4,
                            CocktailId = 2,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 5,
                            CocktailId = 2,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 6,
                            CocktailId = 2,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 7,
                            CocktailId = 2,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 8,
                            CocktailId = 3,
                            IsDeleted = false,
                            Quatity = 1.5
                        },
                        new
                        {
                            IngredientId = 5,
                            CocktailId = 3,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 6,
                            CocktailId = 3,
                            IsDeleted = false,
                            Quatity = 0.5
                        },
                        new
                        {
                            IngredientId = 9,
                            CocktailId = 3,
                            IsDeleted = false,
                            Quatity = 0.25
                        },
                        new
                        {
                            IngredientId = 10,
                            CocktailId = 4,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 11,
                            CocktailId = 4,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 12,
                            CocktailId = 4,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 13,
                            CocktailId = 5,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 14,
                            CocktailId = 5,
                            IsDeleted = false,
                            Quatity = 5.0
                        },
                        new
                        {
                            IngredientId = 6,
                            CocktailId = 5,
                            IsDeleted = false,
                            Quatity = 0.5
                        },
                        new
                        {
                            IngredientId = 15,
                            CocktailId = 6,
                            IsDeleted = false,
                            Quatity = 3.0
                        },
                        new
                        {
                            IngredientId = 16,
                            CocktailId = 6,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 6,
                            CocktailId = 6,
                            IsDeleted = false,
                            Quatity = 0.75
                        },
                        new
                        {
                            IngredientId = 17,
                            CocktailId = 6,
                            IsDeleted = false,
                            Quatity = 0.5
                        },
                        new
                        {
                            IngredientId = 1,
                            CocktailId = 7,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 18,
                            CocktailId = 7,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 3,
                            CocktailId = 7,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 19,
                            CocktailId = 8,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 12,
                            CocktailId = 8,
                            IsDeleted = false,
                            Quatity = 1.0
                        },
                        new
                        {
                            IngredientId = 20,
                            CocktailId = 8,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 21,
                            CocktailId = 9,
                            IsDeleted = false,
                            Quatity = 2.5
                        },
                        new
                        {
                            IngredientId = 22,
                            CocktailId = 9,
                            IsDeleted = false,
                            Quatity = 2.5
                        },
                        new
                        {
                            IngredientId = 13,
                            CocktailId = 10,
                            IsDeleted = false,
                            Quatity = 2.0
                        },
                        new
                        {
                            IngredientId = 17,
                            CocktailId = 10,
                            IsDeleted = false,
                            Quatity = 0.75
                        },
                        new
                        {
                            IngredientId = 6,
                            CocktailId = 10,
                            IsDeleted = false,
                            Quatity = 0.75
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.CocktailReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CocktailId");

                    b.Property<string>("Comment")
                        .HasMaxLength(500);

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("Rating");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CocktailId");

                    b.HasIndex("UserId");

                    b.ToTable("CocktailReviews");
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Unit")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Whiskey",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Angostura bitter",
                            Unit = "dashes"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Sugar",
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Silver Tequila",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Cointreau",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Lime Juice",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Salt",
                            Unit = "pinch"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Citrus Vodka",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Cranberry Juice",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Gin",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Campari",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "Sweet Vermouth",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            Name = "Vodka",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            Name = "Ginger Beer",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            Name = "Mint",
                            Unit = "leaves"
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            Name = "White Rum",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            Name = "Simple Syrup",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            Name = "Lemon Juice",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 19,
                            IsDeleted = false,
                            Name = "Rye Whiskey",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 20,
                            IsDeleted = false,
                            Name = "Angostura bitters",
                            Unit = "dashes"
                        },
                        new
                        {
                            Id = 21,
                            IsDeleted = false,
                            Name = "Champagne",
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 22,
                            IsDeleted = false,
                            Name = "Orange Juice",
                            Unit = "oz"
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "user"
                        },
                        new
                        {
                            Id = 2,
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BannId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("RoleId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "f0476104-41a2-48df-8f15-eb8dc9abbc49",
                            IsDeleted = false,
                            Password = "1283eaf1b5d8f1430e47aeb106f598970762618445a450d575aaba48f85b9b39",
                            RoleId = 2,
                            UserName = "origin"
                        });
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Address", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Bann", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.User", "User")
                        .WithOne("Bann")
                        .HasForeignKey("CocktailMagician.Data.Models.Bann", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.Bar", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.BarCocktail", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.Bar", "Bar")
                        .WithMany("BarCocktails")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailMagician.Data.Models.Cocktail", "Cocktail")
                        .WithMany("BarCocktails")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.BarReview", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.Bar", "Bar")
                        .WithMany("BarReviews")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailMagician.Data.Models.User", "User")
                        .WithMany("BarReviews")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.CocktailIngredient", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.Cocktail", "Cocktail")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailMagician.Data.Models.Ingredient", "Ingredient")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.CocktailReview", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.Cocktail", "Cocktail")
                        .WithMany("CocktailReviews")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailMagician.Data.Models.User", "User")
                        .WithMany("CocktailReviews")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CocktailMagician.Data.Models.User", b =>
                {
                    b.HasOne("CocktailMagician.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
